spring:
  application:
    name: LightIotCloud

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/light_iot_cloud
    username: root
    password: 20041119LYS&lys

  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /graphql

  security:
    user:
      name: admin
      password: 123456

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

extendGraphQlWebSocketHandler:
  pingTimeout: 30s
  checkInterval: 5s

cors:
  allowed-origins: "*"

logging:
  level:
    org.mybatis: DEBUG

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  secret: ~secret~
  expiration: 86400000 # 24小时

image:
  storage-path: "/uploads/"
  thumbnail:
    width: 0.2
    height: 0.2

