spring:
  application:
    name: LightIotCloud

  main:
    banner-mode: off

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/light_iot_cloud
    username: root
    password: 20041119LYS&lys

  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
    websocket:
      path: /graphql

  security:
    user:
      name: admin
      password: 123456

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB


  ai:
    mcp:
      server:
        enabled: true
        name: LightIotCloud-Server
        version: 1.0.0
        type: ASYNC
        sse-message-endpoint: /mcp/message
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true


mybatis-plus:
  configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: PARTIAL

extendGraphQlWebSocketHandler:
  pingTimeout: 30s
  checkInterval: 5s

cors:
  allowed-origins: "*"

logging:
  level:
    org.mybatis: DEBUG
  pattern:
    console:

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  secret: ~secret~
  expiration: 86400000 # 24小时
  wirelessTime : true

image:
  storage-path: "/uploads/"
  thumbnail:
    width: 0.2
    height: 0.2



